name: archery-commons

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - archery/**
            - .github/workflows/archery-commons.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: archery-commons

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: archery-commons
        secrets: inherit
