name: archery-excel

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - archery/**
            - .github/workflows/archery-excel.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: archery-excel

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: archery-excel
        secrets: inherit
