name: archery-parquet

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - archery/**
            - .github/workflows/archery-parquet.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: archery-parquet

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: archery-parquet
        secrets: inherit
