name: archery-csv

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - archery/**
            - .github/workflows/archery-csv.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: archery-csv

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: archery-csv
        secrets: inherit
