name: archery-examples

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - archery/**
            - .github/workflows/archery-examples.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: archery-examples

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: archery-examples
        secrets: inherit
