on:
    push:
        branches:
            - "!main"

jobs:
    build:
        runs-on: [ubuntu-latest]

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   uses: actions/cache@v1
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

            -   name: Installing local dependencies
                run: mvn initialize

            -   name: Build project
                run: mvn -B compile --file pom.xml

    test:
        needs: build
        runs-on: [ubuntu-latest]
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   uses: actions/cache@v1
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

            -   name: Installing local dependencies
                run: mvn install:install-file -Dfile="./libs/nl.fountain/xelem/3.1/xelem-3.1.jar" -DgroupId="nl.fountain" -DartifactId="xelem" -Dversion="3.1" -Dpackaging="jar"

            -   name: Test project
                run: mvn -B test --file pom.xml
